# Generated by Django 4.2.6 on 2023-10-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='author',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='education',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='skills',
        ),
        migrations.DeleteModel(
            name='JobEducation_Experience',
        ),
        migrations.DeleteModel(
            name='JobRequiredSkills',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
